### PR TITLE
Fix interfaces

### LINKED ISSUE #7: Interface Problems when using Verilator
@msfschaffner and I just debugged an interface problem on the atomic adapter side which seems to only appear in Verilator simulation. My suggestion (and I'd volunteer) to switch the interfaces to an exploded interface (single wires) and provide interface wrappers instead of the other way around. That should also fix our creepy hack of the delta-cycle problem.

### PR DESCRIPTION
**Pull request by zarubaf**
This fixes #7 and I can now confirm that actually fixes the problem with Verilator. Also tested with Questa for this infamous delta-cycle loop problem.

### CODE REVIEW

**Comment by andreaskurth** [comment]
Great, thanks! I agree with having flattened ports as default interface.

@SamuelRiedel Can you comment on the changes in https://github.com/pulp-platform/axi_riscv_atomics/pull/9/commits/7628ba65d935e03e86f0bd2eb30e8116d4f3e48f? In particular, I do not see why the default behavior should be feedthrough (https://github.com/pulp-platform/axi_riscv_atomics/pull/9/commits/7628ba65d935e03e86f0bd2eb30e8116d4f3e48f#diff-67c18a48befead32eff3df7330248636L634)?

**Comment by andreaskurth** [comment]
> The changes on the line 679/677 and the additional lines 698-700 are very important. Thanks for pointing them out.

Okay, good; so they go into one commit I would name `axi_riscv_amos: Fix size, burst, and lock of ARs`.

> Whether the default is feedthrough or not is just a matter of style. In this case I prefer not to have feedthrough as all the states except FEEDTHROUGH_AR try to block the channel. In hindsight I prefer to not have feedthrough as default for all the signals. If the aw.size channel was not feedthrough by default, these bugs would have been detected.

I would argue it's more *convention* than style, and since it's safer not to have feedthrough, I suggest we keep them non-feedthrough. @msfschaffner Is that okay with you? Without interfaces there are no more weird simulator bugs on this, right?

> I just also realised that the signals like `ar_cache`, ... , `ar_user` are not handled correctly as they are always in feedthrough.

Okay, please add another commit to fix this.

**Comment by zarubaf** [comment]
After a night of passing CI runs, I can confirm that the weird simulator behavior is gone.

**Comment by msfschaffner** [comment]
@accuminium @SamuelRiedel : sure no problem

**Comment by andreaskurth** [comment]
Perfect, then I will briefly clean up and then merge. Thanks again!

**Pull request merged**
